export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  LOCATION: "Location",
  AMENITIES: "Amenities",
  HOUSE_RULES: "HouseRules",
  PHOTOS: "Photos",
  IMAGE_BROWSER: "ImageBrowser",
  LIST_NAME: "ListName",
  AVAILABILITY: "Availability",
  CALENDAR: "Calendar",
  PRICE: "Price",
});
